#!/bin/bash
# This hook is sourced after every virtualenv is activated.

export PROJECT_NAME=$(basename $VIRTUAL_ENV)
export INFRASTRUCTURE_REPO=$PROJECT_HOME/$PROJECT_NAME/${PROJECT_NAME}-infrastructure
export ANSIBLE_CONFIG=$INFRASTRUCTURE_REPO/config/local/ansible.cfg
export AWS_CONFIG_FILE=$INFRASTRUCTURE_REPO/config/local/aws_config
export KUBECONFIG=$INFRASTRUCTURE_REPO/config/private/kube_config

# Load project specific env variables
if [ -f "$INFRASTRUCTURE_REPO/config/local/vars" ];
then
  source $INFRASTRUCTURE_REPO/config/local/vars
fi

alias ssh='ssh -F $INFRASTRUCTURE_REPO/config/local/ssh_config'
alias scp='scp -F $INFRASTRUCTURE_REPO/config/local/ssh_config'

##
# Helper Functions
##
# Slack Notify (sn)
# Create a Slack incoming-webhook, uncomment the below and supply your webhook url
# To get a notification when a command is done:
# long-running-command ; sn
# function sn {
# curl -s -X POST \
# -o /dev/null \
# --data-urlencode \
# 'payload={ "text": "Done"}' \
# https://WEBHOOK-URL
# }
function sn {
  :
}
