#!/bin/bash
# This hook is sourced after every virtualenv is deactivated.

cd $HOME/workspace


unalias ssh
unalias scp


# TBD, do this programmatically
unset PROJECT_NAME
unset INFRASTRUCTURE_REPO
unset INFRASTRUCTURE_GITHUB_URL
unset AWS_CONFIG_FILE
unset ANSIBLE_CONFIG

# deactivate everything in $INFRASTRUCTURE_REPO/config/local/env_vars
unset AWS_ACCESS_KEY
unset AWS_SECRET_KEY
unset AWS_SECRET_ACCESS_KEY
unset TF_VAR_aws_access_key
unset TF_VAR_aws_secret_key
unset AWS_DEFAULT_REGION
unset AWS_ACCESS_KEY_ID

# zsh errors with the below if the variable/function is not set
unset -f sn
